services:
    mongo:
        image: mongo:6.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: rolebrew
            MONGO_INITDB_ROOT_PASSWORD: rolebrew
            MONGO_INITDB_DATABASE: rolebrewDB
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    rolebrew:
        build: .
        command: packs/ --drop
        working_dir: /app
        ports:
            - "8080:8080"
        environment:
            MONGO_URI: "mongodb://rolebrew:rolebrew@mongo:27017/?retryWrites=true&w=majority&directConnection=true"
        depends_on:
            - mongo
volumes:
    mongo-data:
